# tests/test_jpca.py
#
# The synthetic-validation gate (spec section 3): jPCA must (a) recover a known rotation
# and (b) CATCH the known Lebedev sequence artifact via the triangulation guards. If
# these fail, no real-data jPCA result is trustworthy.

import numpy as np
import pytest

from geometry.jpca import (
    fit_skew,
    fit_full,
    r2_variance_explained,
    dominant_plane,
    jpca_analysis,
    project_pcs,
    state_and_derivative,
)
from geometry.synthetic import (
    make_pure_rotation,
    make_lebedev_sequence,
    make_inconsistent_rotation,
)


# ---- closed-form skew fit ----

def test_fit_skew_recovers_known_matrix():
    """If dX is generated by a known skew M, fit_skew recovers it."""
    rng = np.random.default_rng(0)
    k = 6
    A = rng.normal(size=(k, k))
    M_true = A - A.T                       # skew
    X_all = rng.normal(size=(200, k))
    dX_all = X_all @ M_true.T
    M_hat = fit_skew(X_all, dX_all)
    np.testing.assert_allclose(M_hat, M_true, atol=1e-8)


def test_fit_skew_output_is_skew_symmetric():
    rng = np.random.default_rng(1)
    X_all = rng.normal(size=(100, 5))
    dX_all = rng.normal(size=(100, 5))
    M = fit_skew(X_all, dX_all)
    np.testing.assert_allclose(M, -M.T, atol=1e-12)


def test_full_fit_recovers_general_matrix():
    rng = np.random.default_rng(2)
    k = 4
    M_true = rng.normal(size=(k, k))       # general, not skew
    X_all = rng.normal(size=(300, k))
    dX_all = X_all @ M_true.T
    M_hat = fit_full(X_all, dX_all)
    np.testing.assert_allclose(M_hat, M_true, atol=1e-8)


# ---- fixture 1: genuine rotation must score high and pass the guards ----

def test_pure_rotation_high_r2():
    X, _ = make_pure_rotation(N=30, T=50, C=8, omega=0.15, noise=0.0)
    out = jpca_analysis(X, k=2)
    assert out['r2_skew'] > 0.95


def test_pure_rotation_direction_consistent():
    X, _ = make_pure_rotation(N=30, T=50, C=8, omega=0.15, noise=0.0)
    out = jpca_analysis(X, k=2)
    assert out['direction_consistency'] == pytest.approx(1.0)


def test_pure_rotation_recovers_omega():
    X, omega = make_pure_rotation(N=30, T=50, C=8, omega=0.12, noise=0.0)
    Z, _ = project_pcs(X, k=2)
    X_all, dX_all = state_and_derivative(Z)
    M = fit_skew(X_all, dX_all)
    omega_hat, _ = dominant_plane(M)
    assert omega_hat == pytest.approx(omega, abs=0.01)


# ---- fixture 2: the Lebedev feedforward sequence -- caught by TANGLING ----
# Note: this sequence gives a deceptively HIGH naive jPCA R^2 (~0.87, right at the M1
# anchor) and is even direction-"consistent" (separable g_c * pattern => signed area
# scales as g_c^2, sign-independent). So R^2 and the direction guard do NOT catch it.
# Tangling does -- exactly Russo et al. (2018)'s point.

def test_lebedev_sequence_has_deceptively_high_r2():
    """The artifact must look rotational by R^2 alone -- that's why R^2 isn't enough."""
    X = make_lebedev_sequence(N=30, T=50, C=8, width=3.0)
    out = jpca_analysis(X, k=6)
    assert out['r2_skew'] > 0.6   # high enough to fool a naive reading


def test_lebedev_sequence_caught_by_tangling():
    """The feedforward sequence is substantially more tangled than a genuine rotation."""
    X_seq = make_lebedev_sequence(N=30, T=50, C=8, width=3.0)
    X_rot, _ = make_pure_rotation(N=30, T=50, C=8, omega=0.15, noise=0.0)
    seq = jpca_analysis(X_seq, k=6)
    rot = jpca_analysis(X_rot, k=6)
    assert seq['mean_tangling'] > 3.0 * rot['mean_tangling']


# ---- fixture 3: opposite-rotating conditions -- caught by the DIRECTION guard ----

def test_inconsistent_rotation_caught_by_direction_guard():
    """
    Conditions that rotate in opposite directions are low-tangling (each is a genuine
    rotation) but share no dynamical rule. The direction-consistency guard must fire.
    """
    X = make_inconsistent_rotation(N=30, T=50, C=8, omega=0.15)
    out = jpca_analysis(X, k=2)
    assert out['direction_consistency'] < 0.9


def test_jpca_analysis_keys():
    X, _ = make_pure_rotation(N=30, T=50, C=8)
    out = jpca_analysis(X, k=6)
    assert set(out.keys()) == {
        'r2_skew', 'r2_full', 'skew_gap', 'omega',
        'direction_consistency', 'mean_tangling', 'k',
    }
